### ISSUE TITLE
Working with multiple devices

### ISSUE THREAD

**Issue by Stuart-Burton** [quentinmit/decimctl#1]
Hi Quentin,
Firstly, thank you for this module it has been a great help.
I am very new to coding so apologies if I don't make sense.
I have written a very basic html GET parser for passing commands to a Decimator device.
Unfortunately I found that when I added multiple devices, only one of them would receive commands. It appeared that the _open_device() method was not passing the serial number of the required Decimator.
Your original code:(without indents)

```
   def _open_device(self):
        serial = None
        if self._requested_serial:
            serial = c_char_p(serial)
        return self.fdll.ftdi_usb_open_desc_index(byref(self.ctx), VID, PID, None, serial, 0)
```

The addition of the line below appeared to work. I don't know if there is a better way to do this (highly likely given my level of coding)    
```
def _open_device(self):
        serial = None
        if self._requested_serial:
            serial = self._requested_serial.encode('UTF-8')
            serial = c_char_p(serial)
        return self.fdll.ftdi_usb_open_desc_index(byref(self.ctx), VID, PID, None, serial, 0)
```

**Comment by quentinmit** [comment]
Thank you for the bug report and fix! It was working but I restricted it to ASCII to be safe, and I also improved the error message.
